# varibales at Task level
- name: variables at task level
  hosts: localhost
  tasks:
    vars:
      NAME: vijay
      WIFE: sri
  - name: varibles
    ansible.builtin.debug:
      msg: name is {{NAME}} wife name is {{WIFE}}