# varibales at Task level
- name: variables at task level
  hosts: localhost
  vars:
    NAME: vijay
  tasks:
  - name: varibles
    vars:
      NAME: srivijay
      WIFE: sri
    ansible.builtin.debug:
      msg: name is {{NAME}} wife name is {{WIFE}}