- name: variables from inventory
  hosts: localhost
  tasks:
  - name: varibles from inventory
    ansible.builtin.debug:
      msg: "name is {{NAME}} course name is {{COURSE}} organisation is {{ORGANISATION}}"