- name: Data types
  hosts: localhost
  #become: yes
  vars:
    place: Fruits Market
    frutes:
    - apple
    - grapes
    - watermelon
  tasks:
  - name: fruits List
    ansible.builtin.debug:
      msg: " availabe {{frutes}} place is {{place}}"
