- name: install nginx & git
  hosts: localhost
  become: yes
  tasks:
  - name: install nginx
    package:
      name:
        - git
        - nginx
        - mysql
      state: absent  
    
  
      