- name: redis
  hosts: localhost
  become: yes
  tasks:
  - name: downloading redis app
    ansible.builtin.dnf:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present
      disable_gpg_check: true
  - name: enabling redis:remi
    ansible.builtin.command: dnf module enable redis:remi-6.2 -y
  - name: install redis
    ansible.builtin.service:
      name: redis
      state: present
  - name: replacing ip
    ansible.builtin.replace:
      regexp: '127.0.0.1'
      replace: '0.0.0.0'     
  - name: enabling redis
    ansible.builtin.service:
      name: redis
      enabled: yes    
  - name: start redis
    ansible.builtin.package:
      name: redis
      state: started